### PR TITLE
LPS-60589 Fix how to retrieve translationManager reference

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3673. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/2633593~1...2633593) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3674. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/69c93ae~1...69c93ae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
