### PR TITLE
Lps 60202

### PR DESCRIPTION
**Pull request by ligasm**
Hi @brunobasto @marcellustavares @jbalsas

I'm sending you some improvements to the SoyPortlet. The usage of the template object was not very thread safe so I changed the code to get rid of the global object.

This led to a slight change of the way how the SoyPortlet should be used. I edited the HelloSoyPortlet to the new version.

What do you think?

Miro

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @ligasm, thanks for sending this over!

Could you please update and check the image editor portlet as well? That's the really important one, and we cannot, under any circumstance break it at this point.

I'm on EVP the whole week, so I have very little time to go over this. Please, be specially careful and double check everything is still working after those changes.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ligasm** [comment]
closing this PR and resending to @marcellustavares

@jbalsas I will look at the image editor and update it.

**Comment by jbalsas** [comment]
Thanks @ligasm!

Please, keep in mind that for this to be merged, the image editor part needs to go in at the same time. We are too close to the release to risk anything else, and we have functional tests for it that will fail.

**Pull request closed without merging**
