### PR TITLE
LPS-84994 Generated snapshots

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
Closing to resend again, since I've commited more modifications in this branch

**Comment by clovisdasilvaneto** [comment]
Resend in https://github.com/brunobasto/liferay-portal/pull/925

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62780. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/75a5b4db565e~8...75a5b4db565e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62787. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/6939588b5874~8...6939588b5874) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/855. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/5ac4238dfb42~9...5ac4238dfb42) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
