### PR TITLE
LPS-63422 - Allow parameter selectVal of Liferay.DynamicSelect support more than on value at once.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hey @brunobasto,

This pull request is to add the fix for the issue found by the consulting team in the **Liferay.DynamicSelect**, more details please see [LPSP-172](https://issues.liferay.com/browse/LPSP-172) and the [LPS-63422](https://issues.liferay.com/browse/LPS-63422). If you could prioritize it, the consulting team will appreciate that.

Thanks.

**Comment by natocesarrego** [comment]
retest

**Comment by natocesarrego** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/23. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/7465837~1...7465837) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
