### PR TITLE
LPS-57110 Added validationExpression to DDMFormField

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by pablocp** [comment]
The rest module can be accessed via POST on localhost:8080/o/ddm-eval, sending the serializedDDMForm (json), serializedDDMFormValues (json) and languageId (string) in the request body.

The command
```
curl --data-urlencode "serializedDDMFormValues@serializedDDMFormValues.json" --data-urlencode "serializedDDMForm@serializedDDMForm.json" --data "languageId=\"en_US\"" localhost:8080/o/ddm-eval
```
can be used to test the module from command line, requiring a serializedDDMFormValues.json and a serializedDDMForm.json file to be in the current folder. An example of serialized DDMForm and DDMFormValues can be found on the test commit (64b7ebc)

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/638. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/c195388~1...c195388) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
