### PR TITLE
LPS-66589

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
Bruno, @jonmak08 and I have been attempting to address SEMVER changes to this tickets. Could you review these changes to ensure we haven't broken any API?

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/663. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/d146dfb~1...d146dfb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41624. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/28f4030~1...28f4030) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
