### PR TITLE
LPS-91301 Call autoSave function every time a rule is added or saved after its edition

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72453. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/951a9e1078d4~1...951a9e1078d4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
