### PR TITLE
SFLPS-84334 Csf

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test:relevant

**Comment by clovisdasilvaneto** [comment]
ci:reopen

**Comment by clovisdasilvaneto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
@clovisdasilvaneto, can you rebase and resend? Rebase errors.
Also, can we try to be consistent with event naming? I've seen both fieldAdded and clickedField. We should pick one pattern and stick with it.

Unit tests are failing

Thx

**Pull request closed without merging**
