### PR TITLE
LPS-94091 Element sets cannot call Rule Builder

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/74. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/e24018c33760~1...e24018c33760) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
