### PR TITLE
LPS-97317 Only send event to set the field settings with options when the current field is being edited

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/90. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/7f8e2a6b311f~3...7f8e2a6b311f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
