### PR TITLE
LPS-112928 Fixes error of FieldSet not show repeatable button

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
