### PR TITLE
LPS-68362 Adds an utils class to reorder options

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by lucianasilva** [comment]
ci:reopen

**Comment by fernandosouza** [comment]
ci:reopen

**Comment by fernandosouza** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/562. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/e60aa26~1...e60aa26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
