### PR TITLE
[TECHNICAL-SUPPORT] LPS-69640 Depending on locale add 12 hours to hourOfDay when creating Calendar object

### PR DESCRIPTION
**Pull request by cleydyr**
Relevant issue
https://issues.liferay.com/browse/LPS-69640

/cc @rodrigopaulino

### CODE REVIEW

**Comment by brunobasto** [comment]
@brandizzi, can you take a look at that?

Thanks,

**Comment by brandizzi** [comment]
Sure!

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
It seems reasonable to me and passed my tests here. So, thumbs up to merge.

**Pull request closed without merging**
