### PR TITLE
LPS-71378 Frontend

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:stop

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1869. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/99c6cf3~1...99c6cf3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1870. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/ca81dcf~2...ca81dcf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
