### PR TITLE
LPS-110397 Disables some interactions with Fieldsets after they have been added to the Form

### PR DESCRIPTION
**Pull request by brunobasto**
ince Fieldsets are essentially references to another Form (and for the sake of simplicity) it makes sense that the user shouldn't be able to modify it by adding fields or removing fields from it directly from where its being used. Rather, the user should edit the Fieldset on its own Form Builder. For now Fieldsets are being treated as a rigid group when they are used in another form.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:stop

**Comment by brunobasto** [comment]
ci:close

**Pull request closed without merging**
