### PR TITLE
LPS-72504 This method is now inherited

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by fernandosouza** [comment]
ci:reopen

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
@brunobasto, I just rebase this pull. Is there anything else missing that is blocking push forward?

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
Hey, @brunobasto. Is there anything missing?

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49064. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/79216bd~1...79216bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @fernando, I'm just fixing some issues with the backend rendering performance of soy and will merge this asap. Thx

**Pull request closed without merging**
