### PR TITLE
LPS-66646

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-66646.

Since this touches quite a few different components, I figured we should send this to you to review and get the approval of the various components leads as well.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brunobasto** [comment]
/cc @juliocamarero @pei-jung @drewbrokke @carloslancha

Hey guys, when you have some time, I'd like to know if you are ok with these changes since it touches your modules.

Thanks,

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
@jbalsas @brunobasto hey guys! Looks good. Just one thing, before this changes, on the asset publisher configuration scope selector when you opened the modal to add a site, you could select a site already added, then form was submited, window was closed and nothing happened because site was already added, but action occurred.

Now you can click a site already added but nothing happens, there's no feedback to the user (for example an alert or something warning the user why the action can't be done, or already added sites with some opacity... I don't know, something).

That's the only "weird" behaviour I notice but don't know exactly which should be the correct one.

**Comment by jonmak08** [comment]
Hey @zxdgoal,

Do you have any input/feedback regarding the issue @carloslancha mentioned above?

**Comment by zxdgoal** [comment]
Hey @carloslancha 

I believe neither the behaviours without our fixes nor the one with our fixes are flawless.

Before this changes, the user can re-select one site from the AP scope selector. But this action does not make any sense as it dose not have any effects on AP. The end user could not realize the site he is choosing the one currently displayed on AP(I assume he has a bad memory).

After this changes, the end user cannot re-select the chosen site in AP. This could also be weird for him as he could forget this one is currently displayed in AP again and no feedback to him after clicking on the site.

Back to our fixes, for the buttons, as we added  ``disabled`` for un-selectable  options, their color become grey and the end user can easily distinguish them when selecting options. But for links, this is not the case. All the links looks the same regard less of being selected or not.

So, it is the journal team the to choose to change using links from buttons. And they should be aware of this limitation.

But from a more general perspective, it could be more user-friendly to give feed backs(hits) when selecting a selected option on UI for both buttons and links

Just some of my thoughts

**Comment by juliocamarero** [comment]
@brunobasto @jbalsas would this be a reason for using the buttons pattern everywhere instead of the link? If so, we can change our forms to use always buttons.

**Comment by jonmak08** [comment]
Hey @juliocamarero,

I think that would be a reason to use the button pattern, because with buttons you have a disabled state that you can control to disallow people from selecting certain options.  With links, you have no such ability.

**Comment by juliocamarero** [comment]
Hey guys, 

looking into some of our lexicon patterns, I think we will need to work on the links stuff. See this screenshot, lexicon pattern suggests that the whole card should be clickable. We can't add a button there. We probably need to the lexicon team to them to find a way to have "disabled" elements.

public_pages_-_liferay

I wouldn't stop this pull for that reason, but I think we should starting working on this. What do you think @jbalsas?

**Comment by brunobasto** [comment]
Hey guys,

Looks like everyone is ok with the change, but there are improvements to discuss. I'll send this over and we can continue talking about this here or somewhere else.

Thanks,

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44270. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/d14b6c7~0...d14b6c7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
