### PR TITLE
LPS-97251 Enable filling in text field with multiple lines on IE11 / Edge

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76762. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/d903c0149d65~1...d903c0149d65) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76763. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/5cebe68546be~1...5cebe68546be) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
