### PR TITLE
LPS-61139 Quick fix - Correct parsing of positional day of week.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
Apparently, POSHI broke at the Control Panel (as far as I've seen the testcase and macro files). Trying to see if a sync'ed branch has it solved.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3720. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/25783a2~1...25783a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
