### PR TITLE
LPS-94728 Do not get field type or datatype when operand type is field or user

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72375. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/5e80dd37a651~1...5e80dd37a651) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
