### PR TITLE
LPS-108480 Migrate Options to React

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
hey @brunobasto, I will close this PR and send it to me, I will agglomerate the other fields in this PR https://github.com/matuzalemsteles/liferay-portal/pull/27

**Comment by brunobasto** [comment]
Thank you

**Pull request closed without merging**
