### PR TITLE
LPS-65551

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunobasto,

Attached is an update for http://issues.liferay.com/browse/LPS-65551.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Trying to leverage ```screenActivate``` event for SPA instead.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/kenjiheigel/liferay-portal/pull/207. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/2e8e541~2...2e8e541) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
