### PR TITLE
LPS-68782 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
I'll resend this

**Comment by marcellustavares** [comment]
It seems to be a fluke

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/607. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/4b8aabbf~1...4b8aabbf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
