### PR TITLE
LPS-68011 SF

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/593. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/b51b016~1...b51b016) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
