### PR TITLE
LPS-59278 Unable to edit radio, select fields which embedded in other field in DDL Spreadsheet View fields

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3669. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/0a97250~1...0a97250) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
