### PR TITLE
LPS-61568 buildLang

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
@marcellustavares,

@fernandosouza will resend parts of this PR separately and other parts after integrating with clipboardjs

**Comment by fernandosouza** [comment]
@marcellustavares, I sent to @brunobasto the part of this PR which solve this issue https://issues.liferay.com/browse/LPS-61740

I will apply clipboard.js as soon as possible.

**Comment by marcellustavares** [comment]
awesome @fernandosouza this was the better approach.

Thanks

**Pull request closed without merging**
