### PR TITLE
LPS-67192 - In SPA Configuration, a zero value in cache expiration time disables cache

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Bruno,

Attache is an update for https://issues.liferay.com/browse/LPS-67192.

These changes
1) fix the functionality of cache expiration times to:

```
-1 -> disable
0 -> never ending
x -> custom
```

2) change milliseconds input to seconds for request timeout and user notification timeout.

Please let me know if any of this functionality is wrong.  It was a little hard for me to wrap my head around exactly the best way this should work.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mjbradford89, @brunobasto, just a note on this... why the switch to seconds instead of milliseconds? It is common to have those configuration in milliseconds and I guess we have many like that around, so better stay consistent...

Is there some specific reason for this?

**Comment by mjbradford89** [comment]
Hey @jbalsas, I think the only reason we had to change to seconds was to be more intuitive for the user when changing these settings.  Whichever way we decide it shouldn't affect any other changes in this pull.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41826. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/634c75a~1...634c75a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey guys, sorry I didn't answer before. Isn't this an API breaking change? Imagine you had configured your SPA timeout to 10000, now it won't be the same. I don't think we can keep this this way. Another option is we document it properly, but then we probably cannot backport it to ee-7.0.x...

**Comment by brunobasto** [comment]
Hey guys,

I think Chema is right. I didn't pay attention to the breaking change in
the request timeout. Was more concerned with the user notification timeout.

I'm going to revert this.

**Comment by mjbradford89** [comment]
Hey @jbalsas @brunobasto,  Thanks for catching that and reverting it!  Was there anything else needed from my end?

**Comment by brunobasto** [comment]
No, I think that was it.

Thanks!

**Pull request closed without merging**
