### PR TITLE
LPS-94199 Add method to know if field was duplicated

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72349. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/4893e8d754b7~1...4893e8d754b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
