### PR TITLE
LPS-56601

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Bruno, I did a lot of source formatting in here (not any major refactoring or code movement, though), but could you test it to make sure I didn't break anything? If it's all okay, go ahead and send over to Brian. Thanks Bruno!

### CODE REVIEW

**Comment by brunobasto** [comment]
Heya @natecavanaugh,

Are we allowed to use native forEach and map for arrays now?

Does check_sf check for unused vars?

I'll test it right now.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
@natecavanaugh 

Everything is working as expected. Thanks

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28133. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/84a1683d~0...84a1683d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natecavanaugh** [comment]
Heya Bruno,
Yeah, you can use ES5 methods now :) https://issues.liferay.com/browse/LPS-55654

**Comment by brunobasto** [comment]
Nice!

**Pull request closed without merging**
