### PR TITLE
LPS-112781 Avoids generating a new name all the time

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:forms

**Comment by brunobasto** [comment]
ci:test:app-builder

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:bundle

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
Hey @brunobasto , I just cross-checked your results with the latest results of the app-builder routine executed on CI (https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1142871999).

The analysis follows below:

**Known issue in App Builder suite**

- AccessAndSetPermissionsForCustomObject;
- MakeSureIsNotPossibleSaveEmptyFormView;
- PredefinedValuesArePersistedInFormView;
- RemoveFormViewFields;
- SetAppBuilderManagePermissionFor2RolesAndPerformCRUD.

**Only failing in your PR**

- ReuseExistingFormViewFields -  for some reason was not possible to add the Single Selection field ;
- CreateTableViewsWithFixedEntriesFilter - a delay happened after adding an entry (when clicking in the Save button, so was not possible to validate the entry in the table);
- ViewEntryDetails - flaky in this execution, seems to be a race condition issue;
- CreateRemoveUpdateDeleteEntriesOfStandaloneApp - a delay happened after adding an entry (when clicking in the Save button, so was not possible to validate the entry in the table);
- CreateRemoveUpdateDeleteEntriesOfWidgetApp - a delay happened after adding an entry (when clicking in the Save button, so was not possible to validate the entry in the table);
- CreateRemoveUpdateDeleteEntriesOfProductMenuApp - a delay happened after adding an entry (when clicking in the Save button, so it was not possible to validate the entry in the table);.


And looking at the history of these tests, they are passing in other PR executions, so I would suggest you re-rerun.

Best Regards,
Alex.

**Comment by alexcandidos** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
ci:test:relevant

**Pull request closed without merging**
