### PR TITLE
DDM Select Field

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
** Rebased with the current master **
Hey @john-co, Could you take a look on the failing tests? I'm getting some troubles when comparing with https://github.com/brunobasto/liferay-portal/pull/1113 baseline and I'm not sure if these fails are okay or not.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1067312469&testrayRunIdA=1067285968&statusB=2

[related] - [AppBuilder#CreateRemoveUpdateDeleteEntriesOfProductMenuApp](https://testray.liferay.com/reports/production/logs/test-1-6/1584976493891/test-portal-acceptance-pullrequest(master)/5921/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.AppBuilder_CreateRemoveUpdateDeleteEntriesOfProductMenuApp/index.html.gz) - need to manually verify if regression or test fix
[related] - [AppBuilder#CreateRemoveUpdateDeleteEntriesOfStandaloneApp ](https://testray.liferay.com/reports/production/logs/test-1-6/1584976493891/test-portal-acceptance-pullrequest(master)/5921/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.AppBuilder_CreateRemoveUpdateDeleteEntriesOfStandaloneApp/index.html.gz) - need to manually verify if regression or test fix
[fluke] - AppBuilder#PublishAppsInProductMenuAndReuseItsViews
[fluke] - AppBuilder#ReuseExistingFormViewFields
[flaky] - AppBuilder#UnpublishAndRepublish

**Comment by john-co** [comment]
**Forms Results:**

**Comparison of unique failures:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1067310642&testrayRunIdA=1067283894&statusB=2

- [related] - FormRules#ConfigureAutofillRule
-- FormsDataProvider#ConfigureWithSelectField
-- FormsDataProvider#ViewDataRetrievedForGuestUser
```java.lang.RuntimeException: Element is not present at "//div[contains(@data-field-name,'outputParameters')]//div[contains(@data-field-name,'outputParameterType')]//button"```

- [related] - Forms#SubmitFormAfterEditingFields
-- Forms#SubmitFormWithAllFieldTypesAndThreePages
-- FormsUpgrade#ViewAndDeleteFormEntryAfterUpgrade70106
-- FormsUpgrade#ViewAndDeleteFormEntryAfterUpgrade704
-- Forms#DeleteSelectFromListOptionAndViewEntries
```java.lang.RuntimeException: Element is not present at "//p[contains(text(),'Select') or contains(@for,'Select')]/following-sibling::div[contains(@class,'ddm-select-dropdown') or contains(@class,'input-group-container')]//button | //div[contains(@data-field-name,'Select') or contains(@for,'Select')]//following-sibling::div[contains(@class,'ddm-select-dropdown') or contains(@class,'input-group-container')]//button"```

- [related to old baseline] - Forms#SubmitFormWithCustomTextContainingValidation
```java.lang.RuntimeException: Element is not present at "//div[contains(@class,'has-error')]//div[contains(@class,'form-feedback-item')] | //div[contains(@class,'has-error')]//div[contains(@class,'form-feedback-indicator')]"```

- [related] - Forms#SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay
```java.lang.RuntimeException: Element is not present at "//p[contains(text(),'SelectField') or contains(@for,'SelectField')]/following-sibling::div[contains(@class,'ddm-select-dropdown') or contains(@class,'input-group-container')]//button | //div[contains(@data-field-name,'SelectField') or contains(@for,'SelectField')]//following-sibling::div[contains(@class,'ddm-select-dropdown') or contains(@class,'input-group-container')]//button"```
- [fluke?] - FormRules#ViewShowRuleActivationAfterInputtingUnrelatedField

- [related] - Forms#EditFormsConfigurationViaSystemSettings
```java.lang.RuntimeException: Element is not present at "//p[contains(text(),'Default Display View') or contains(@for,'Default Display View')]/following-sibling::div[contains(@class,'ddm-select-dropdown') or contains(@class,'input-group-container')]//button | //div[contains(@data-field-name,'Default Display View') or contains(@for,'Default Display View')]//following-sibling::div[contains(@class,'ddm-select-dropdown') or contains(@class,'input-group-container')]//button"```

- [flaky] - Forms#ViewConfirmationWhenLeavingFormWithoutSaving
```java.lang.Exception: Expected text "Elements" does not match actual text (case insensitive) "" at "//a[contains(@class,'tab') and .='Elements'] | //a[contains(@class,'nav-link active') and .='Elements']"```

**Comment by john-co** [comment]
ci bundle still pending.

cc/ @zhangyan0701, would you be able to continue with this and verify the related issues?

**Comment by zhangyan0701** [comment]
Just started reviewing :)

**Comment by zhangyan0701** [comment]
**App-builder Results:**

**Comparison:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1067312469&testrayRunIdA=1067285968&statusB=2

[related] - AppBuilder#CreateRemoveUpdateDeleteEntriesOfProductMenuApp
              - AppBuilder#CreateRemoveUpdateDeleteEntriesOfStandaloneApp

Select from List field doesn't display as a drop down menu in the new deployed app:

**Comment by brunobasto** [comment]
Closing in favor of https://github.com/diegonvs/liferay-portal/pull/12

**Pull request closed without merging**
