### PR TITLE
LPS-94509 Fix the query which selects the back button and update href

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72357. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/71cd13ebb802~2...71cd13ebb802) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
