### PR TITLE
LPS-65903 Change the presentation behaviour of validation feedback

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@brunobasto Please forward to @marcellustavares when you're done. Thanks !!!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/373. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/251dc59~2...251dc59) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1446. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/251dc59~2...251dc59) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
