### PR TITLE
LPS-69556 Fixes the missing button's data in the request on Liferay.Util.submitForm() method

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @fernandosouza, lots of broken tests, I'd say these are real failures :/

**Comment by fernandosouza** [comment]
Hey, @jbalsas. I'm going to investigate it.

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
@jbalsas @brunobasto. Everything is green now. :)

**Comment by jbalsas** [comment]
awesome! :)

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49930. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/5fc833c80381~1...5fc833c80381) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
