### PR TITLE
LPS-69587 Add task to run test in ci

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by brunobasto** [comment]
@diogo-lins Deu esse erro no CI:

TypeError: themeDisplay.getDefaultLanguageId is not a function (/opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/js/field.js:44)

Sabe o que pode ser?

**Comment by diogo-lins** [comment]
@brunobasto Yeah, I know why this happened, in the liferay-karma-alloy-config, in the npm repo is missing this function, I sent to you a pull request with this on 10 Nov. So you need to merge this, after that, the npm package will be downloaded with this function, this works with me because I put this fucntion locally.

**Comment by brunobasto** [comment]
Hey @diogo-lins, I merged the pull request you sent today but I didn't see any pull requests from 10 Nov: https://github.com/brunobasto/liferay-karma-alloy-config/pulls?q=is%3Apr+is%3Aclosed

Is it on another repo?

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
Also, @diogo-lins do we need to update the package.json for the tests to work?

**Comment by diogo-lins** [comment]
Yes, you are right. May I send another commit with this change?

**Comment by brunobasto** [comment]
Yes, please.

**Comment by diogo-lins** [comment]
I checked in the package.json and in this line:
"liferay-karma-alloy-config": "^0.0.12", is caret(ˆ) present, don't you think that is sufficient to works well?

**Comment by brunobasto** [comment]
Probably, let's see what the CI outputs this time.

Thanks,

**Comment by diogo-lins** [comment]
You're welcome,

**Comment by brunobasto** [comment]
@diogo-lins, I saw a source format error on the CI, but it might be unrelated to your changes. Can you run "ant format-source" from portal-impl/ and send this PR to Victor Ware?

Thanks,

**Comment by brunobasto** [comment]
Actually, I'm not sure the JavaScript tests run.

@kenjiheigel, can you take a look at https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/66865/? 

I'm not sure what happened there.

Thanks

**Comment by diogo-lins** [comment]
@brunobasto I ran the "ant format-source" and no one file was affected after that. This SourceFormatterTest.testSourceFormatter is about changes in the gradle-plugin-node, and I didn't nothing in this files.

**Comment by diogo-lins** [comment]
Was missing a rebase with the master, so the CHANGELOG.markdown was haven't the line "[LPS-69677]: https://issues.liferay.com/browse/LPS-69677", now this is there.

**Comment by kenjiheigel** [comment]
@brunobasto, taking a look.

**Comment by kenjiheigel** [comment]
@brunobasto, @diogo-lins, the tests are trying to run on Chrome, which we don't have available on these Jenkins servers right now. Could you guys update the karma config to use Firefox? 

> 
     [exec] [17:24:43] Starting 'test'...
     [exec] [17:24:43] Starting 'soy'...
     [exec] [17:24:43] Finished 'soy' after 38 ms
     [exec] [17:24:43] Starting 'test:unit'...
     [exec] [33m14 12 2016 17:24:44.018:WARN [watcher]: [39mPattern "/opt/dev/projects/github/liferay-portal/modules/apps/foundation/frontend-js/frontend-js-web/node_modules/metal-soy-bundle/build/bundle.js" does not match any file.
     [exec] [33m14 12 2016 17:24:44.020:WARN [watcher]: [39mPattern "/opt/dev/projects/github/liferay-portal/modules/apps/foundation/frontend-js/frontend-js-web/node_modules/html2incdom/src/*.js" does not match any file.
     [exec] [32m14 12 2016 17:24:45.595:INFO [karma]: [39mKarma v1.3.0 server started at http://localhost:9876/
     [exec] [32m14 12 2016 17:24:45.595:INFO [launcher]: [39mLaunching browser Chrome with unlimited concurrency
     [exec] [32m14 12 2016 17:24:45.601:INFO [launcher]: [39mStarting browser Chrome
     [exec] [31m14 12 2016 17:24:45.601:ERROR [launcher]: [39mNo binary for Chrome browser on your platform.
     [exec]   Please, set "CHROME_BIN" env variable.
     [exec] [17:24:45] Finished 'test:unit' after 2.23 s
     [exec] [17:24:45] Finished 'test' after 2.27 s
     [exec] 
     [exec] :apps:foundation:frontend-js:frontend-js-web:testJS
     [exec] 
     [exec] BUILD SUCCESSFUL
     [exec] 
     [exec] Total time: 2 mins 15.194 secs
     [exec] Gradle build finished at 2016-12-15 01:24:45.624

**Comment by kenjiheigel** [comment]
Two different issues actually, the Chrome issue is because of the frontend-js-web test.. Will investigate further.

**Comment by brunobasto** [comment]
Hey @kenjiheigel, so the ones from dyanmic-data-mapping-type-select run successfully?

**Comment by kenjiheigel** [comment]
@brunobasto, no, one of the tests fail: 
https://gist.github.com/kenjiheigel/48918bacd1299b4abf961587eb3f98c3

Does that pass locally?

**Comment by brunobasto** [comment]
Hey @kenjiheigel, the tests were actually failing locally too due to a missing version of a package on NPN. It should be fixed now. We are only gonna fix a warn message on the log and try running it again.

As far as the `frontend-js-web` test trying to run on Chrome, we don't know why it's trying to do that. We are using the browsers configuration from `liferay-karma-config`. See https://github.com/brunobasto/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-select/karma.conf.js#L2

**Comment by brunobasto** [comment]
BTW, the Poshi tests are expected to fail. We'll fix those later.

**Comment by kenjiheigel** [comment]
@brunobasto, was going to ask about those poshi tests haha. The frontend-js-web module was recently updated to use Chrome actually, so I sent Ambrin a fix to go back to firefox: 
https://github.com/ambrinchaudhary/liferay-portal/pull/122

**Comment by brunobasto** [comment]
Oh, that explains it :)

**Comment by kenjiheigel** [comment]
Yeah haha. As for the actual test failure from dynamic-data-mapping-type-select , I ran it locally and it failed on both Chrome and Firefox locally for me.. so that will probably be something for you guys to look into. Let me know if you need anything else though!

**Comment by brunobasto** [comment]
Yeah. @diogo-lins sent me another PR: https://github.com/brunobasto/liferay-portal/pull/800

Hopefully they will pass now.

**Pull request closed without merging**
