### PR TITLE
LPS-60155 Now we mark the hidden field as required instead as it meets the syntax for naming in ddm_repeatable_fields.js

### PR DESCRIPTION
**Pull request by marcellustavares**
@brunobasto, could you please review this? Thanks

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
hey @zxdgoal,

I can still reproduce the issue with repeated Images and Document Library fields. Reproduced the issue repeating a Document Library field or an Image field.

**Comment by zxdgoal** [comment]
Sorry Bruno

My steps are in LPS could be not precise.

So the issue is : 

1. Create a structure with required and repeated Text field, with a required DM field as its child.
2. Fill the Text and upload a file for DM field.
3. Repeat the Text field
4. Only fill the Text field and leave DM field blank for the repeated Text field.
5. Publish

You should fail as the repeated DM field is required.

I tried again.

The issue is not there.

Thanks
John.

**Comment by zxdgoal** [comment]
Some explanation:

When repeating DDM field, the input name should meet the syntax.

See 
```
					getFieldInputName: function(fieldNode) {
						var instance = this;

						var portletNamespace = instance.get('portletNamespace');
						var namespace = instance.get('namespace');

						var prefix = [portletNamespace];

						if (namespace) {
							prefix.push(namespace);
						}

						return prefix.concat(
							[
								fieldNode.getData('fieldName'),
								fieldNode.getData('fieldNamespace')
							]
						).join('');
					},
```

For DM field, the name of what to be validated is appended with Title.

This leads to a bad naming.

I changed to hidden field to be validated as it meets the standard of naming.

Thanks
John

**Comment by brunobasto** [comment]
Hey @zxdgoal

I understood your changes, however ai can still reproduce the issue where if you create a Document Library field and set it as repeatable and required the form only validates the first instance of the field but doesn't validate the repeated entries.

**Comment by zxdgoal** [comment]
You are right. It seems that _afterUpdateRepeatableFields isn't triggered in this case. That is strange.

**Comment by zxdgoal** [comment]
Hey Bruno

The issue is that DocumentLibraryField extend Field, which extends base.

So, for DocumentLibraryField and Field, NAME will be added as a prefix to the events fired by them.

Because Field has a name: 'liferay-ddm-field' while DocumentLibraryField does not have a NAME as static fields will not be inherited, only Field works.

So the solution would be adding 'liferay-ddm-field' as NAME for all the fields, e.g. imageField, DocumentLibraryField etc?

It would be confusing that a few fields with the same name.

What are your ideas?

Thanks
John.

**Comment by zxdgoal** [comment]
I sent a new pr here:https://github.com/brunobasto/liferay-portal/pull/303

**Pull request closed without merging**
