### PR TITLE
LPS-98047 Only show label tag when there is a label and showLabel is active or if field is required, it has tooltip or it is repeatable

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75664. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
