### PR TITLE
LPS-84279 update snapshot

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62938. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/67e545b70148~1...67e545b70148) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
