### PR TITLE
LPS-90724 Fix localizationMap missing initialized values for newly created repeatable fields

### PR DESCRIPTION
**Pull request by linolaoj**
@brunobasto , please see https://github.com/jeyvison/liferay-portal/pull/230#issue-254439075
Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
Hello @brunobasto,

Can you let us know if you think you will be able to take a look at this soon? Thanks!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68713. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/7b0bdc656fa5~1...7b0bdc656fa5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
