### PR TITLE
LPS-70309

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:reopen

**Comment by shinnlok** [comment]
ci:reopen

**Comment by shinnlok** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @shinnlok, @brunobasto, the other day I realized that [SoyJavaScriptRenderer](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-template/portal-template-soy/src/main/java/com/liferay/portal/template/soy/utils/SoyJavaScriptRenderer.java#L33) is probably affected by this as well.

Could you guys take a look to make sure we fix this in both places?

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
