### PR TITLE
LPS-111610 Position data engine sidebar in journal

### PR DESCRIPTION
**Pull request by victorg1991**
Hey @brunobasto 

You can ignore the last two commits, they include some adaptations that we need for journal but don't apply in other places like data engine or documents & media :)

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/interaminense/liferay-portal/pull/27.

**Comment by brunobasto** [comment]
@victorg1991 Changes look good to me. I sent them to @interaminense so that he could do some tests on App Builder.

Thank you

**Comment by victorg1991** [comment]
Thanks @brunobasto :)

**Pull request closed without merging**
