### PR TITLE
LPS-110013 Removes AlloyEditor from the Forms portlet

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @mateomustapic, I've fixed [here](https://github.com/brunobasto/liferay-portal/pull/1150/commits/a7c89b6c463eb92af8e3cf7c313f03b5d67c2d0e) the selectors for name and description. Since we are not using AlloyEditor anymore the selectors should match `input` elements instead of `div` elements. Also, I've made the selector be more specific so that they don't accidentally match with other inputs that have an id with the word "name" or "description" in it.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Comment by brunobasto** [comment]
ci:forward

**Comment by brunobasto** [comment]
@mateomustapic Should I close this one? I saw you closed the others.

**Comment by mateomustapic** [comment]
> @mateomustapic Should I close this one? I saw you closed the others.

Yes plesase, close it

**Pull request closed without merging**
