### PR TITLE
LPS-98372 Add dependency

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
/cc @rodrigopaulino 

@brunobasto please forward to BChan after your review

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @brunobasto.

Do you have any estimate on concluding this review? Sorry to bother you with that but I just got this question from the Customer Support Engineer who's reported this issue.

Best.

**Comment by brunobasto** [comment]
If that's ok, I'll get to it this afternoon and hopefully send to Brian today.

**Comment by rodrigopaulino** [comment]
Sure. It's ok. Thanks for the quick reply, Timão.

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77408.

**Pull request closed without merging**
