### PR TITLE
LPS-65503 Array.find() is not supported in IE11. Use Array.some() instead

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39437. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/692e474~1...692e474) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thanks @ambrinchaudhary!

**Pull request closed without merging**
