### PR TITLE
LPS-60016

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Bruno,
I did some general source formatting, but I'm sending this one over to you to have you review the latest commit.
I _think_ we can do all of this inside of one loop, but there might be some reason why we can't that you would know better than me.
Can you review this, and if all is good, send over to bchan?

Thanks Bruno!

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @natecavanaugh 

Thanks! This is working fine. I think I'll have to take JavaScript 101 again because while writing this I thought doing

    var events = instance._domEvents;

    instance._domEvents = [];

would also set ``events`` by reference to an empty array. Go figure :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31635. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/5d5b77c~0...5d5b77c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natecavanaugh** [comment]
LOL, no worries, it's an easy thing to forget, especially when you're doing a ton of changes.
Thanks for pushing it up to Brian :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/294. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/89932b1~1...89932b1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31646. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/8da2dd0~2...8da2dd0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
