### PR TITLE
LPS-85803 Update snapshots

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:reopen

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/49. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/d312ec52cf1b~1...d312ec52cf1b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64192. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/50bd6cade596~5...50bd6cade596) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
