### PR TITLE
LPS-68850

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunobasto,

Attached is an update for http://issues.liferay.com/browse/LPS-68850.  I sent this to you just as another set of eyes before sending this in.  In the icon taglib, we are calling

```
svg4everybody(
    {
        polyfill: true
    }
);
```

to render a polyfill for the SVG icons in browsers that cannot render the external SVGs.  I went ahead and added this call to all the JS calls in portal that are bringing in external SVG icons since they are not rendering IE9, 10, or 11.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @jonmak08, I don't know much about svg4everybody, but, looking at the project description, seems like it's only supposed to be called once per page load. Do you know if that's the case?

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/natecavanaugh/liferay-portal/pull/4092

**Pull request closed without merging**
