### PR TITLE
LPS-58972 Fix return type

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@brunobasto I just fixed return type and applied some source format

**Comment by leoadb** [comment]
@brunobasto I mentioned the correct LPS in my commits, the one that we talked about.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/924. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/6a37dad~0...6a37dad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/925. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/8132d2e~0...8132d2e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
