### PR TITLE
[Technical Support] LPS-65353

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @Alec-Shay 

https://issues.liferay.com/browse/LPS-65353

From Alec:

> In master, DDMStructureIndexerBackgroundTaskExecutors (along with their entire serialized context maps) would be left in the database indefinitely without a need for them, and without an easy way to remove them any time a LAR import or staging publish caused a re-index for DDM structures using DDMStructureIndexer (see DDMStructureLocalServiceImpl's reindexStructure()). For very large imports/publishes, these could potentially cause concerns with the amount of space used in the database.
> 
> A similar effect exists in 6.2, where StagingIndexingBackgroundTaskExecutors would be left in the database with no purpose for any page import/publish.
> 
> This fix allows the DDMStructureIndexerBackgroundTaskExecutors to be removed once they are completed, and also adds a VerifyProcess to be able to remove any StagingIndexingBackgroundTaskExecutors that might still exist as the result of an upgrade.

### CODE REVIEW

**Comment by dustinryerson** [comment]
Pull for ee-6.2.x here: https://github.com/brunobasto/liferay-portal-ee/pull/38

**Comment by achaparro** [comment]
Hi @Alec-Shay, @dustinryerson,

This commit https://github.com/brunobasto/liferay-portal/pull/564/commits/97c0fa81f06643d4f6a599de854225df7deb918d has to be implemented as an upgrade process if there is not an strong impediment to it. Please, check it.

We are trying to avoid to create verifiers that modifies data in Liferay 7.

Thanks.
@migue, @jorge-lr

**Comment by Alec-Shay** [comment]
Hello @achaparro ,

Thanks for the tip, I can change that.

I am pretty confused though about what the difference between an upgrade process and a verify process should be for Liferay 7. I thought that a verify process was the right way to do this, because I thought verify processes were exactly for modifying data. What are they supposed to be for in Liferay 7?

**Comment by achaparro** [comment]
Hi @Alec-Shay,

Both to Liferay 7 and earlier Liferay versions, if there is something we need to change/modify between 2 versions of Liferay must always to be done in an upgrade process. It is possible that you need to fix a bug which modifies data in the middle of a release so it could be feasible to create a verify process for that but not in master (just in the old branch)

We want to be more restrictive with verifiers in Liferay 7 because a verify is executed in every new version (this could add performance issues) and we have to maintain for all life. However an upgrade process is just for proper upgrade path and once fixes the issue is not executed again.

Taking this into account we should achieve not to create more verifiers for modifying data and all these kind of process should be consider as upgrade processes (at least in master).

Please, let me know if you have any doubt regarding this. If everything is ok for you, please, spread this message to all your workmates. I will also try to create a wiki once I finished all pending tasks.

Thanks.

**Comment by Alec-Shay** [comment]
@achaparro Thank you for the explanation! That makes sense.

I still am not sure exactly where (as in what version) this upgrade process should be in though -- I suppose it would be in the portal-background-task module, but since this process would just be cleaning up data but not changing the structure of anything, maybe it could still go in the v1_0_0 module package for it? I am not confident about that though, because I notice the portal's UpgradeProcess in portal-impl went from 7_0_0 to 7_0_1 as the one still being apparently updated, but I have no idea why there was a cut-off, or if it's completely different from how the module versions are decided. Maybe it still needs a new version because it's been a while since the last commits updating it?

Sorry I have so many questions! I just want to make sure I put things in the right place, but I don't know how to decide where.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @Alec-Shay,

Answering your questions:
_Maybe it still needs a new version because it's been a while since the last commits updating it?_
I guess it should be in a new version for that module (check the proper number, perhaps v1_0_1) since users using Liferay 7 CE GA1 will need to fix that problem too.

_Also, I notice that many of the already implemented upgrade processes directly query the database to do what they're doing. Since all kinds of things might be upgraded is that preferable to using a service like I was previously?_
For all previous Liferay versions we had to use direct SQLs in the upgrade processes since the API could change between versions so we could get an error during the upgrade. Right now, for a module upgrade you should use direct SQL for tables from that module but you could use the API if you call services for other modules (since a module shouldn't know the database schema for other modules). So, taking into account the nature of your upgrade process, you should use direct SQL.

Please, talk also with @SamZiemer about this since I think he could help you in person.

Thanks.

**Comment by Alec-Shay** [comment]
Will do. Thank you, @achaparro

**Comment by brunobasto** [comment]
@dustinryerson It looks like it's all backend stuff. Can you send it to Marcellus?

**Pull request closed without merging**
