### PR TITLE
LPS-62767

### PR DESCRIPTION
**Pull request by kenjiheigel**
Hey @brunobasto, I know you guys aren't in the office this week, but just sending this up. Some java packages were updated, so I made the appropriate changes so I can run tests on this again.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brunobasto** [comment]
Hey Kenji, I'll be in the office starting tomorrow.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
K, thanks for the heads up Bruno. I'll try to have some results by EOD today.

**Pull request closed without merging**
