### PR TITLE
LPS-101419 | Apply new Portlet URL util in document library utils

### PR DESCRIPTION
**Pull request by boton**
Hi @boton ,

The changes in this PR are on two utils in frontend-js-aui-web, used in DL modules.

Please review the code.

Thank you!

/cc @jbalsas @kresimir-coko

### CODE REVIEW

**Comment by boton** [comment]
Hi @brunobasto after a talk with @jbalsas I'll send this to you for review if something breaks DDM.
Thanks in advance.

**Comment by jbalsas** [comment]
Hey @brunobasto, do you think you'll get a chance to look at this one? Since it's ddm, not sure where else to go with it. 

You could also maybe just give us some testing pointers so @markocikos can double-check and make sure this is ok.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by brunobasto** [comment]
Hey guys, sorry. I was planning to get to it last week, but ended up not being able to. I’ll take a look at it today by EOD. 
Thx

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78766.

**Pull request closed without merging**
