### PR TITLE
LPS-99236 Removes no longer necessary code

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @jbalsas, forgot to ask. What should we be using instead? Just replace this code with vanilla?

**Comment by jbalsas** [comment]
Hey @brunobasto, I'd say just use `clipboard.js` for now as you're already doing in this same module. We'll see if we need to provide a general API for copy/paste in the future.

**Comment by brunobasto** [comment]
Ah, got it. I got confused. You actually removed dead code. Thanks!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76856. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
