### PR TITLE
[TECHNICAL-SUPPORT] LPS-56554 Dynamic Data List boolean field cannot be set to required on the UI

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-56554

Hi Bruno,

Ed asked me to forward this to you: https://github.com/eduardolundgren/liferay-portal/pull/500#issuecomment-118070778

-- quote --
Hi Eduardo,

Hope you're doing well. :-]

I'm forwarding this pull to you, as you added 'required' to the hidden metadata attributes of the boolean field in @f019abf in LPS-21981.
-- end quote --

However, the template allows to mark a boolean field as "required": https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/dynamicdatamapping/dependencies/alloy/checkbox.ftl Actually, the "aui:validaton" was added to the template in LPS-21981 as well: @15edbf5

So, I don't see any cons not to accept István's solution.

Let us know if you had any concern.

Regards,
Tibor

@IstvanD

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @lipusz,

I think it was done on purpose. When would the checkbox return an empty value? If it's checked the value is ``true``, if it's not checked the value is ``false``. We can add the required option, but I don't think it's ever gonna be validated, you know what I mean?

**Comment by lipusz** [comment]
Hi Bruno,

I absolutely agree with, though from another perspective, we have a
template that is designed to include an aui:validation tag if the field is
set to be required.

So, I'd ask István to remove that from the ftl then.

What do you think?

Thx,
Tibor

@IstvanD

Sent from mobile
--
Senior Software Engineer @TS
Security SME, Subscription Services & Release, Global

Hey @lipusz <https://github.com/lipusz>,

I think it was done on purpose. When would the checkbox return an empty
value? If it's checked the value is true, if it's not checked the value is
false. We can add the required option, but I don't think it's ever gonna be
validated, you know what I mean?

—
Reply to this email directly or view it on GitHub
<https://github.com/brunobasto/liferay-portal/pull/207#issuecomment-118927697>
.

**Comment by brunobasto** [comment]
Hey @lipusz 

Yeah, I guess that makes more sense. Thanks

**Comment by lipusz** [comment]
Alright.

@IstvanD: please, remove the mentioned parts from the template and resend.

Thank you, Bruno! Have a good evening!

Sent from mobile
--
Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global

**Pull request closed without merging**
