### PR TITLE
LPS-94291 Add specific methods to show ElementSets groups and another when there's no element sets

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @brunobasto, I don't think the failed tests are related to the PR.

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72350. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/e088a6af0be6~1...e088a6af0be6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
