### PR TITLE
LPS-94106 Change predefinedValue and value types to be number or string

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73046. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/f82016478032~2...f82016478032) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
