### PR TITLE
LPS-112839 Fixes Sidebar error when closing and opening when editing a field

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
