### PR TITLE
Revert "LPS-66561 This check is not longer needed." This function is used in other places (e.g. quick edit popup.)

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @brandizzi,

Regarding the revert of the latest commit, I was analyzing it and it was used (apart from main view of calendar portlet) just for the quick edit popup (as you have said). Taking that into account, does it make sense to hide the calendar resource name for calendars called like the calendar resource name? For example, if we have added two calendars from other site called Liferay, one called liferay and other called events, you will see:
- Liferay
- Liferay - Activities
Among other calendars, it wouldn't be confused for the user? He would see some calendars with resource names and a few without it and perhaps he would ask himself about to which site belongs those calendars.

I am not asking you to add this commit, I just want to know your opinion since for me it's a bit confused.

Thanks!

**Comment by brandizzi** [comment]
Hello @achaparro!

That's an excellent question. This behavior was decided long time ago, before I even worked at Liferay. Yet, it makes sense to me because it leaves the UI less cluttered. Also, there is a very common scenario where only default calendars are listed (no extra calendar is created for sites/users):

only-default-calendars

In this situation, adding the resource name seems unnecessary, I'd say it even seems buggy:

calendar-resource

So far, I have found no confusion with the current behavior, no customer or user asked about that. I know I'm biased, but it looked understandable to me as well :)

Of course, this can be changed any time if needed. Since now it is a long-held, intentional behavior with no complaints, I reverted it. Yet, if you find a user got confused by that, let me know! We can work on that.

Thanks!

**Comment by brunobasto** [comment]
Sorry, didn't mean to close this one :)

**Comment by brunobasto** [comment]
ci:stop

**Comment by achaparro** [comment]
Hi @brandizzi,

I had't thought about that scenario regarding using just default languages. Taking into account your explanation I also agree to discard the latest commit.

Thanks!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40911. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/9539cf5~0...9539cf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/414. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/9539cf5~0...9539cf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
