### PR TITLE
LPS-66295 WIP - JS

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
I think this breaks the Form save in English.

after0

**Comment by brunobasto** [comment]
Hey Victor, this is a work in progress. We should have mentioned in the pr. Thanks

**Comment by vicnate5** [comment]
@brunobasto  WIP. Got it :)

**Pull request closed without merging**
