### PR TITLE
LPS-94091 SF

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73552. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/fbce76d98b78~2...fbce76d98b78) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
