### PR TITLE
LPS-63642 DM folder with documents inside cannot be deleted without a page refresh

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
### WorkflowCalendar#ApproveEventWithInvitedUser: 
**Bug - Workflow redirects to wrong page.**
_Steps:_
1. Add a page with a Calendar portlet
2. Navigate to the "Workflow Configuration" and set "Single Approver" for "Calendar Events". 
3. Add a Calendar event
4. Navigate to the "My Workflow Tasks" portlet
5. Click on the "Assigned to My Roles" task
6. Click on the actions ellipsis icon for the added event, then click "Assign to Me" then click "Done"

_Expected results:_
There should be a success message. 

_Actual results:_
Page redirects here:
incorrect redirect

**Comment by brunobasto** [comment]
@kenjiheigel I've seen this. Working on that right now.

Thanks,

**Comment by kenjiheigel** [comment]
@brunobasto, k. Same thing happens when you delete a page from the Site Pages portlet (by clicking the ellipsis icon > Delete).

**Comment by kenjiheigel** [comment]
And it looks like the rest of the failures are from the Workflow redirect as well. Sorry for the delay in getting back to you, but I think that should account for all the issues.

**Pull request closed without merging**
