### PR TITLE
LPS-114697 Deprecates <clay:table>

### PR DESCRIPTION
**Pull request by brunobasto**
This PR marks `<clay:table>` and related APIs as deprecated. Right now I've marked them as _"with no direct replacement"_, but in reality, we have plans to build a replacement. It just doesn't exist yet.
For more information, check the progress on https://issues.liferay.com/browse/IFI-1044

/cc @jbalsas

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> Right now I've marked them as "with no direct replacement", but in reality, we have plans to build a replacement.

We can always undeprecate it :)

**Comment by brunobasto** [comment]
True :)

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
