### PR TITLE
LPS-69587 fix warn messenge log tests

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by brunobasto** [comment]
@kenjiheigel, looks like it passed now, right?

**Comment by kenjiheigel** [comment]
@brunobasto, yep, looks like it did! 
https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/62375/AXIS_VARIABLE=0,label_exp=!master/testReport/Firefox%2038.0.0%20(Linux%200.0.0)/

**Comment by brunobasto** [comment]
Cool! Thanks, @kenjiheigel!

@diogo-lins, can you forward it to Clarissa?

Thank you all!

**Comment by diogo-lins** [comment]
Yes, sure!

Thanks @brunobasto and @kenjiheigel

**Pull request closed without merging**
