### PR TITLE
LPS-60471 Handle properly the existence of both use and require modules

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey Bruno, I these are real errors. Metal.js is mutating the dom objects, so code like this will fail:

```javascript
var button = $('#buttonId');

button.on('click', function(event) { ... });

new Dropdown({
    element: '#buttonId
}).render();

console.log(button === $('#buttonId')); // false -> click listener is lost
```

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Working on fixing the issues...

**Pull request closed without merging**
