### PR TITLE
LPS-67961 SF

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
@thiago-rocha poshi failures

**Comment by marcellustavares** [comment]
@brunobasto, please don't forget to update the LPS.

**Comment by brunobasto** [comment]
@marcellustavares sure, thx

**Pull request closed without merging**
