### PR TITLE
LPS-97960 Set z-index do 1200 to show the dropdown that was below the modal

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
si:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76251. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
