### PR TITLE
LPS-51718 Prevent duplication when user accesses its own site

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3599. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/4db2813~1...4db2813) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31630. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/4db2813~1...4db2813) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
