### PR TITLE
LPS-66296

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brunobasto I closed the previous PR since I had to fix a few issues.  The last remaining issue is the display of the web content title.  My comments from previous PR apply

@igorarouca you can pull this pr down and run your import/export test locally as well.  Outside of the minor UI bug, everything else should work.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40492. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/e9e09fc~1...e9e09fc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
