### PR TITLE
Name of the select or radio field options do no update with label changes. We have a front end test, Forms#SubmitFormWithAllFieldTypesAfterEditingFields that will fail due to this regression.

### PR DESCRIPTION
**Pull request by vicnate5**
Sending https://github.com/vicnate5/liferay-portal/pull/384 back to you. Found a regression. The "Field Name" of the select or radio field options do no update with label changes. We have a front end test, Forms#SubmitFormWithAllFieldTypesAfterEditingFields that will fail due to this regression.

### CODE REVIEW

**Comment by vicnate5** [comment]
renameoptions

**Comment by vicnate5** [comment]
ci:stop

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/thiago-rocha/liferay-portal/pull/9. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/854688d~1...854688d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
