### PR TITLE
LPS-98077 Add support to move fields between sections and create a section by moving a field over another one (all levels)

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by jbalsas** [comment]
I think this can be closed, @brunobasto, remember to push your changes to me or @carloslancha when you have the chance so we can try to continue while you guys are at carnival! :)

**Comment by brunobasto** [comment]
Hey @jbalsas, sorry I couldn’t find time to send you or Carlos a PR about this sooner. I’ll push what I have first thing tomorrow.

**Comment by brunobasto** [comment]
Latest PR is here: https://github.com/brunobasto/liferay-portal/pull/1127

**Pull request closed without merging**
