### PR TITLE
LPS-72770

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunobasto,

Attached is an update for http://issues.liferay.com/browse/LPS-72770.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
Please see https://github.com/SamZiemer/liferay-portal/pull/281#issuecomment-304276714 for more details.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49441. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/b49fdfb~0...b49fdfb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
