### PR TITLE
LPS-57333 Make a non localizable field readonly in case of display language is different from the default one

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Thanks @leoadb!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3506. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/2e44eae~1...2e44eae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
