### PR TITLE
LPS-75443 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52464. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/1fda29859f25~1...1fda29859f25) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
