### PR TITLE
LPS-97612 Fix the select from list width in user view to reflect the field width set on form builder

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75342. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/63a5fd957205~1...63a5fd957205) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
