### PR TITLE
LPS-109492 Fixes the regression that made the option "Add Success Page" disappear from the Forms portlet.

### PR DESCRIPTION
**Pull request by brunobasto**
It seems that the regression was caused by a confusion on what `successPageSettings.enabled` actually does. The `successPageSettings` configuration of the Form Builder has the following structure:

```
{
    body: "A success message to the end user",
    title: "A success message title to the end user",
    enabled: true // or false
}
```

The `enabled` property tells the Form Builder if the success page feature is currently enabled in the form. That is: When a user (**End User**) submits a response to a form he/she will be redirected to this success page.

Recently we needed a feature that would say if the **Form Builder User** (the user that actually creates the form) is able to define a success page to a form or not. That feature was added by reusing the `successPageSettings.enabled` flag and that is what caused the confusion.

I've now added a new configuration called `allowSuccessPage` that's meant to remove the "Add Success Page" option from the Form Builder when set to `false`.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
Hey @brunobasto,

Thanks for running Forms test suite!

Your pull is addressing the CI issues associated to LPS-109492. Please, rebase this branch with the latest master and run `ci:forward`. Now, I believe there are no failures which will block `ci:forward`succeed. 🙂 

Thanks.

**Comment by brunobasto** [comment]
Thanks, @natocesarrego. I'm aware of ci:forward. I have been trying ti get stuff in the entire week. Something always fails. Will try it now and we will see.

**Comment by brunobasto** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Resent in https://github.com/natocesarrego/liferay-portal/pull/421.

**Pull request closed without merging**
