### PR TITLE
LPS-90579 setting required properties

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70416. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
