### PR TITLE
LPS-111233 Replace <liferay-ui:input-editor> with <liferay-editor:editor> in calendar-web

### PR DESCRIPTION
**Pull request by mateomustapic**
The goal of this change is to replace liferay-ui:input-editor
(which was deprecated in 7.1.0) with liferay-editor:editor in calendar-web.
The behaviour and looks of editor after these changes should be the same, also the build should be successful after deploy the module with new gradle dependency.

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by mateomustapic** [comment]
ci:stop

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/543.

**Pull request closed without merging**
