### PR TITLE
LPS-92870 Remove default value

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71880. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/eaf0db635e83~4...eaf0db635e83) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
