### PR TITLE
LPS-92863 Keep using type when second operand if different from numeric types

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71876. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/cb4c9968e33a~1...cb4c9968e33a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
