### PR TITLE
LPS-64204 Hide header content if scheduler does not display header.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
Hey @brunobasto! You were spot on! There was a difference between the component names. Let's say if it works now.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/517. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/4eeee9c~0...4eeee9c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
