### PR TITLE
LPS-69389 Update type-select

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brunobasto, I'm sending this over just so you can start playing around with it.

I've made the necessary changes to get things to render. Stop all the other `ddm-type-*` bundles other than the modified here (which seem to be the minimal ones needed for forms to run).

Escaping is broken, eval as well, and in the creation part, the tabbed fields do not show... so I'm not very confident, but please, take a look and let me know what you think.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/357. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
