### PR TITLE
LPS-84275 Generated snapshots

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test:relevant

**Comment by clovisdasilvaneto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
