### PR TITLE
LPS-55819

### PR DESCRIPTION
**Pull request by marcellustavares**
Hey @marcellustavares,

Attached is an update for http://issues.liferay.com/browse/LPS-55819. I sent this to you for review since you added this at 94ad3c2a677fd530b150f99c2eed8e5094a1528f.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by marcellustavares** [comment]
Thanks @jonmak08, I've sent to @brunobasto for final review.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3432. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/7bc7a3b~0...7bc7a3b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
