### PR TITLE
LPS-93230 Do not replace previous newField properties related to dataSourceType fieldName

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73044. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/d3de47c33a45~3...d3de47c33a45) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73047. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/aa32de38ff5d~3...aa32de38ff5d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
