### PR TITLE
LPS-110013 Replace AlloyEditor in Description and Title fields in Forms

### PR DESCRIPTION
**Pull request by mateomustapic**

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by mateomustapic** [comment]
ci:stop

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
@mateomustapic I'll work on https://issues.liferay.com/browse/LPS-109492 before forwarding it to Brian because that's making some tests fail for Forms and we won't be able to merge it this way.

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1150. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/a7c89b6c463e~1...a7c89b6c463e)

**Pull request closed without merging**
