### PR TITLE
LPS-65976 Disables unnecessary tasks

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
ci:reetest

**Comment by brunobasto** [comment]
ci:retest

**Pull request closed without merging**
