### PR TITLE
LPS-87289 Update unit tests to getDepth method

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test

**Comment by jpince** [comment]
@brunobasto can you please revert 1e176451a60c9fb1d1d81bc8533f13c23c7d49af when you push this to BChan? I removed the portal-frontend-js batch from relevant so it doesn't fail other people's PRs.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/interaminense/liferay-portal/pull/13. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/9d92d7071ca4~1...9d92d7071ca4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
