### PR TITLE
LPS-63870

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunobasto,

Attached is an update for http://issues.liferay.com/browse/LPS-63870.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
@jonmak08 @mjbradford89 There are a lot of poshi failures. Do you guys know if they are related?

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
Let me see if they are related to this.  I know the failures are coming from SPA...

**Comment by mjbradford89** [comment]
Hmm these failures weren't happening on https://github.com/jonmak08/liferay-portal/pull/1503. but I'll look into them.

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jonmak08** [comment]
I'm going to rebase and retest.

**Comment by jonmak08** [comment]
ci:retest

**Comment by mjbradford89** [comment]
Thanks Jon.  I wasn't able to reproduce any of these failures manually.  I also rebased and sent a pull to myself but got a different failure :cry:  https://github.com/mjbradford89/liferay-portal/pull/79

**Comment by brunobasto** [comment]
hey guys,

https://github.com/mjbradford89/liferay-portal/pull/79#issuecomment-193973226 doesn't have any failures. Can I go ahead and merge this one in?

**Comment by brunobasto** [comment]
Closing, @jonmak08 will send it to Brian.

Thanks, guys.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/37303

**Pull request closed without merging**
