### PR TITLE
LPS-67304

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunobasto,

Attached is an update for http://issues.liferay.com/browse/LPS-67304.  Can you check to make sure this fixes all the date picker issues we were seeing?

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
Closing and sending to @juliocamarero instead.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/juliocamarero/liferay-portal/pull/4219

**Pull request closed without merging**
