### PR TITLE
LPS-85359 Remove URLEncodedFetcher and extend from Component

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/48. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/07cd265d1921~7...07cd265d1921) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
