### PR TITLE
LPS-63870

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunobasto,

Attached is an update for http://issues.liferay.com/browse/LPS-63870.

NOTE: This issue was caused by `Liferay.Data.layoutConfig` being undefined when `Liferay.Layout.init()` is called after navigation([App.es.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/platform/frontend/frontend-js-spa-web/src/main/resources/META-INF/resources/liferay/app/App.es.js#L97)).  It's not defined because in [top_js.jspf](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/common/themes/top_js.jspf#L84), we redefine `Liferay.Data` in a script block that has `data-senna-track=temporary`.  So from what I understand based on @brunobasto's comments on slack, this means this code will be ran after every navigation.

It looks like cd57f5976f846820ed81b6ed632885d81350fcba was originally intended to prevent this from happening, but doesn't seem to work when there is an editor on the page.  I'm thinking this is because the editor takes some time to load.

So by making the `layoutConfig` definition `data-senna-track=temporary` as well, it should ensure it is defined." - @mjbradford89 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
I also created this ticket (https://issues.liferay.com/browse/LPS-63977) and assigned it to @kienD to remove the ```type="text/javascript"``` from all ```<script /> tags that are using ```javascript``` for consistency in the portal code.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
Thanks for reviewing this one guys.

Hmm interesting. In that case I think what's happening then is that the layout definition just isn't defined in time for when the `endNavigate` event is fired.

In that case I think we could just change how `Liferay.Data` is defined in top_js.jspf, so that it does not overwrite the entire object after every navigation.  We're doing something similar for the Liferay global.

If that sounds good I'll send it to Jon and you can close this pull.

Thanks!

**Comment by jonmak08** [comment]
Closing pull based on @mjbradford89's comments.

**Comment by mjbradford89** [comment]
new pull: https://github.com/jonmak08/liferay-portal/pull/1503

**Pull request closed without merging**
