### PR TITLE
LPS-99125 Replace element 'closest' method by metal-dom closest method to be compatible with IE11

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76611. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
