### PR TITLE
LPS-93027 Set predefinedValue properties when changing from Text(or other fields which don't receive array values) to Select, Radio and Multiple checkbox and vice-versa

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75116. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/2dda6feb8a9c~2...2dda6feb8a9c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
