### PR TITLE
LPS-58771 Unregister component after dispose it.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @xbrianlee The failing test seems unrelated, right?

Thx

**Comment by xbrianlee** [comment]
Hi @brunobasto, the PACL test appears to be related to be related to the changes for soy template in this pull:
```
com.liferay.portal.kernel.process.ProcessException: java.lang.AssertionError: Thread Thread[Framework Event Dispatcher: Equinox Container: 9086df2c-8b36-0017-1c2e-d6027f34f444,5,] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com_liferay_portal_template_soy, message=FrameworkEvent ERROR 
java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com_liferay_portal_template_soy, message=FrameworkEvent ERROR 
	at com.liferay.portal.test.rule.LogAssertionAppender.append(LogAssertionAppender.java:61)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at com.liferay.portal.log.Log4jLogImpl.error(Log4jLogImpl.java:54)
	at com.liferay.portal.kernel.log.LogWrapper.error(LogWrapper.java:69)
	at com.liferay.util.sl4fj.LiferayLoggerAdapter.error(LiferayLoggerAdapter.java:110)
	at com.liferay.portal.equinox.log.bridge.internal.PortalSynchronousLogListener._log(PortalSynchronousLogListener.java:97)
	at com.liferay.portal.equinox.log.bridge.internal.PortalSynchronousLogListener.logged(PortalSynchronousLogListener.java:76)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:88)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:217)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory$3.run(ExtendedLogReaderServiceFactory.java:184)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory$3.run(ExtendedLogReaderServiceFactory.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:182)
	at org.eclipse.osgi.internal.log.LogServiceManager.frameworkEvent(LogServiceManager.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:929)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.IllegalStateException: There are no bundles providing 325_BUNDLE_CONTEXT_/META-INF/resources/metal-progressbar/src/ProgressBar.soy
	at com.liferay.portal.template.soy.internal.SoyProviderCapabilityBundleRegister.getTemplateBundle(SoyProviderCapabilityBundleRegister.java:46)
	at com.liferay.portal.template.soy.internal.SoyTemplateBundleResourceParser.getURL(SoyTemplateBundleResourceParser.java:46)
	at com.liferay.portal.template.URLResourceParser.getTemplateResource(URLResourceParser.java:49)
	at com.liferay.portal.template.DefaultTemplateResourceLoader._loadFromParser(DefaultTemplateResourceLoader.java:283)
	at com.liferay.portal.template.DefaultTemplateResourceLoader.getTemplateResource(DefaultTemplateResourceLoader.java:147)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourceLoader.getTemplateResource(SoyTemplateResourceLoader.java:68)
	at com.liferay.portal.kernel.template.TemplateResourceLoaderUtil._getTemplateResource(TemplateResourceLoaderUtil.java:126)
	at com.liferay.portal.kernel.template.TemplateResourceLoaderUtil.getTemplateResource(TemplateResourceLoaderUtil.java:53)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourcesCollector._getTemplateResource(SoyTemplateResourcesCollector.java:146)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourcesCollector.collectProviderBundlesTemplateResources(SoyTemplateResourcesCollector.java:102)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourcesCollector.getTemplateResources(SoyTemplateResourcesCollector.java:52)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourcesTracker$SoyCapabilityBundleTrackerCustomizer._addTemplateResourcesToList(SoyTemplateResourcesTracker.java:155)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourcesTracker$SoyCapabilityBundleTrackerCustomizer.addingBundle(SoyTemplateResourcesTracker.java:116)
	at com.liferay.portal.template.soy.internal.SoyTemplateResourcesTracker$SoyCapabilityBundleTrackerCustomizer.addingBundle(SoyTemplateResourcesTracker.java:94)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:905)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:79)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:77)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:461)
	at org.eclipse.osgi.container.Module.start(Module.java:452)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1510)
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:415)
	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:231)
	at com.liferay.portal.test.rule.PACLTestRule.<clinit>(PACLTestRule.java:389)
	at com.liferay.portal.security.pacl.test.JNDITest.<clinit>(JNDITest.java:35)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at com.liferay.portal.kernel.test.junit.BridgeJUnitTestRunner.runBridgeTests(BridgeJUnitTestRunner.java:51)
	at com.liferay.portal.security.pacl.PACLAggregateTest$PACLTestsProcessCallable.call(PACLAggregateTest.java:326)
	at com.liferay.portal.security.pacl.PACLAggregateTest$PACLTestsProcessCallable.call(PACLAggregateTest.java:283)
	at com.liferay.portal.kernel.process.local.LocalProcessLauncher.main(LocalProcessLauncher.java:122)
```

**Comment by brunobasto** [comment]
Oh, sorry I missed that! Thank you!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49007. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/f5eb9d2~0...f5eb9d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
