### PR TITLE
LPS-96253 Remove Success page from layout state

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74949. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/09d708ed4dd7~1...09d708ed4dd7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
