### PR TITLE
LPS-69939 Keep AUI .tld description when regenerating

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Bruno,

I've added the taglib description (found in `liferay-aui.tld`) to the `liferay-aui.xml` file. This fixes the issue of the description being removed during regeneration. Thanks!

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @codyhoag, I see that the LPS is already closed. Does this PR still need to be merged?

Thx

**Comment by codyhoag** [comment]
Hey @brunobasto; this was a side issue reported in brianchandotcom#45885. This PR is related to [LPS-69939](https://issues.liferay.com/browse/LPS-69939), but is a separate issue. This should still be merged, if it looks OK to you.

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46113. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/20d833f~2...20d833f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
