### PR TITLE
LPS-84991 Create tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/clovisdasilvaneto/liferay-portal/pull/65. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
