### PR TITLE
LPS-94150 Completely display footer of Delete field modal by overwriting justify-content css property of Clay to be compatible with IE11 and other browsers

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77447.

**Pull request closed without merging**
