### PR TITLE
LPS-70926 Resets all Portlets before screen flip

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by jbalsas** [comment]
Thanks @fernandosouza, this looks good and should do the trick! It is just a bit weird to me, though that we do this kind of global effects in a `screen` instance. I think this should rather be handled at the `App` level instead.

**Comment by fernandosouza** [comment]
Hey, @jbalsas. Branch updated. 😃

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@fernandosouza @jbalsas @brunobasto 

The `Forms#SubmitFormContainingCaptchaAndViewTextFieldValue` failure has been quarantined by Victor here: https://github.com/brianchandotcom/liferay-portal/pull/48215. The `PGTags#RemoveTagViaBlogs` failure is an inconsistent failure that QA is aware of.

**Comment by jbalsas** [comment]
LGTM, thanks a lot @fernandosouza!

**Comment by jbalsas** [comment]
Hey @brunobasto, I noticed we're never cleaning up the `Liferay.on` handlers here... I guess we're never going to be destroying/recreating the App, but it is potentiall risky to leave those hanging. Do you think we should do something about that?

**Comment by brunobasto** [comment]
Hey @jbalsas, I think we could probably do that on the dispose of the app, although that will never be called, at least we don't have any mechanism to dispose the app yet. The App will live as ling as the page is not reloaded.

**Comment by jbalsas** [comment]
Yeah, it's fine for now... let's just keep in mind that we are setting global listeners around there... just in case :)

Can you push this forward?

Thanks!

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48314. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/f1d73c7~0...f1d73c7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
