### PR TITLE
LPS-77775 Use appropriate data-senna-track attributes

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
ci:test

**Comment by stiemannkj1** [comment]
ci:test

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55831. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
