### PR TITLE
LPS-110013 Standardize container widths

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @mateomustapic, because we are in stabilisation period I sent myself this and will run the CI and ask the QA for Forms to check the results before sending this to BChan

**Comment by brunobasto** [comment]
ci:testy:forms

**Comment by brunobasto** [comment]
ci:stop

**Comment by brunobasto** [comment]
ci:test:forms

**Comment by brunobasto** [comment]
ci:test:app:builder

**Comment by brunobasto** [comment]
ci:test:bundle

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
He @mateomustapic, I see some failures from poshi related to reading the title and description values. Since we moved form alloy editor to a simple input we need to change the poshi selectors. See `java.lang.RuntimeException: Element is not present at "//div[contains(@id,'nameEditorContainer')]/div"`.

**Comment by mateomustapic** [comment]
ey @brunobasto can you close this one? 
New PR with modified code https://github.com/brunobasto/liferay-portal/pull/1144

**Pull request closed without merging**
