### PR TITLE
LPS-84097 SF

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62175. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/b74f61f254bc~3...b74f61f254bc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
