### PR TITLE
LPS-67821 Implement new translation manager in journal

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @brunobasto I'm getting some errors when I try to use the taglib. Could you please take a look? Thanks!

(The pr is closed because the journal sub-repo stuff...)

cc @jbalsas

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @carloslancha, I'm looking at it now.

Thx

**Comment by brunobasto** [comment]
@migue,

I'm not sure what's going on here. Looks like the [TranslationManagerTag](https://github.com/brunobasto/liferay-portal/pull/808/commits/a179b0cc5313f847101abd37a02e59b2c6bdcea2#diff-83d2c41ef1f53267e590748369723050) doesn't get loaded. Which is odd because all other classes in this module are loaded. Maybe the JspAnalyzer is not requiring the right version (which I doubt). The only thing different about this class is that it extends from a class that lives inside another module: https://github.com/brunobasto/liferay-portal/blob/master/modules/apps/foundation/frontend-taglib/frontend-taglib-soy/src/main/java/com/liferay/frontend/taglib/soy/servlet/taglib/TemplateRendererTag.java#L46. Which should be fine the that class is inside an exported package.

Here's the stacktrace: https://gist.github.com/brunobasto/a9edacb05d5abe922bad701e649ec92e

Can you give us a hand when you have some time?

Thx

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
/cc @carloslancha @jbalsas

@migue discovered a bug in the JSPAnalyzer plugin and I filed an issue: https://issues.liferay.com/browse/LPS-69894

Once this is fixed, @carloslancha can move on with this.

Thx,

**Comment by jbalsas** [comment]
Awesome, thanks a lot, guys!

**Comment by carloslancha** [comment]
Great, thank you!

**Comment by migue** [comment]
You don't need to wait for a fix. Add this

Require-Capability:\
osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=
http://liferay.com/tld/soy))"

In the bnd.bnd file of your Journal-web module

On Dec 28, 2016 6:34 PM, "Carlos Lancha" <notifications@github.com> wrote:

Great, thank you!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brunobasto/liferay-portal/pull/808#issuecomment-269511088>,
or mute the thread

**Comment by carloslancha** [comment]
Awesome @migue ! Thanks! It's working now! :D

**Pull request closed without merging**
