### PR TITLE
LPS-97386 Remove z-index from Form settings modal in order to not cover the control panel

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75344. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
