### PR TITLE
LPS-63602 Component to listen to session expiration; then it disables some things.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by vicnate5** [comment]
CC @michaelhashimoto @pyoo47
build failure

**Comment by pyoo47** [comment]
This failure occurred because of a problem on repository.liferay.com. A fix for this in progress. I think we should see an end to these issues by tomorrow.

https://issues.liferay.com/browse/LRQA-23237

```
deploy:
      [bnd] 1 ERRORS
      [bnd]  Failed to download plugin /opt/dev/projects/github/liferay-portal/util-bridges/../.bnd/ant-baseline-cache/com.liferay.util.bridges-2.0.0.jar from https://repository.liferay.com/nexus/content/repositories/liferay-releases-ce/com/liferay/portal/com.liferay.util.bridges/2.0.0/com.liferay.util.bridges-2.0.0.jar, error java.io.IOException: Server returned HTTP response code: 502 for URL: https://repository.liferay.com/nexus/content/repositories/liferay-releases-ce/com/liferay/portal/com.liferay.util.bridges/2.0.0/com.liferay.util.bridges-2.0.0.jar
      [bnd] /opt/dev/projects/github/liferay-portal/util-bridges/bnd.bnd: bnd failed
      [bnd] 	at aQute.bnd.ant.BndTask.executeBackwardCompatible(BndTask.java:203)
      [bnd] 	at aQute.bnd.ant.BndTask.execute(BndTask.java:84)
```

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37752. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/8dec031~1...8dec031) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
