### PR TITLE
LPS-110252 Fix field click event bug.

### PR DESCRIPTION
**Pull request by oliveiraaraujo**

### CODE REVIEW

**Comment by oliveiraaraujo** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86516. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/8c53fabbf225~2...8c53fabbf225)

**Pull request closed without merging**
