### PR TITLE
LPS-94290 Create methods to support pages handling which are been used by RuleEditor and RuleList classes

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72374. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/c3967c5adbb9~1...c3967c5adbb9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
