### PR TITLE
LPS-52917

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey @brunobasto 

This fix is trying to fix https://issues.liferay.com/browse/LPS-52917 and  https://issues.liferay.com/browse/LPS-52998

Please help reviewing

Thanks
John.

**Comment by brunobasto** [comment]
Hey, @zxdgoal, Thanks for the fix!

I´ve already implemented that exactly same fix in a pull that is yet in review, so I'll close this one. See: https://github.com/brunobasto/liferay-portal/commit/a2649edabef52abe8d6c54e2527500cf1327d577

**Comment by zxdgoal** [comment]
Hey @brunobasto 

I believe you omitted one fix in your commit.

In line 696 of ddm_form.js
```
					updateTranslationsDefaultValue: function() {
						var instance = this;

						var parent = instance.get('parent');

						var translationManager = parent.get('translationManager');

						var localizationMap = instance.get('localizationMap');
```
we do not need to get ``translationManager`` from ``parent`` now. We can get it from ``instance`` directly.

No sure if you include this in your other's prs. If not, please change it.

Thanks
John.

**Comment by brunobasto** [comment]
Hey @zxdgoal, thanks for pointing that out. I'll make sure to include this change in the pull.

**Comment by brunobasto** [comment]
And here it is: https://github.com/brunobasto/liferay-portal/commit/ca45d7efeb0ecf8405d980b72f34e66fa2ec363

**Comment by zxdgoal** [comment]
@brunobasto  did you merge the fix into Trunk?

I saw LPS-51921 is closed

Thanks
John.

**Comment by brunobasto** [comment]
Hey John,

It was fixed by recent changes made for LPS-52998 and LPS-60589.

Thanks,

**Pull request closed without merging**
