### PR TITLE
LPS-111674 The language selector popup doesn't close by clicking on another language at system settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111674](https://issues.liferay.com/browse/LPS-111674).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@brunobasto would you be willing to take a look at my solution? Please let me know if we need to approach this differently. Thanks!

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
LGTM

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
