### PR TITLE
LPS-94388 Send the locale where the copied label must be placed

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72376. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/91f02bb22a71~1...91f02bb22a71) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
