### PR TITLE
LPS-97253 Check if target is an empty row

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75744. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/febcfe3127f5~2...febcfe3127f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75745. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/c66de9b283a6~2...c66de9b283a6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
