### PR TITLE
LPS-95117 Add container-input-field-index attribute

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73052. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/bbefa82a6a5f~1...bbefa82a6a5f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
