### PR TITLE
LPS-67961 Setting state true to value attribute on the Validation Field

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
ci:reset

**Comment by thiago-rocha** [comment]
ci:reset

**Comment by thiago-rocha** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

The test failure is not related to this pull.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/537. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/487a85f~1...487a85f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
