### PR TITLE
LPS-59017 Fix visual to options

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by fernandosouza** [comment]
I have other suggestions. We can discuss that later.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/brunobasto/liferay-portal/compare/b6f60de~0...b6f60de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
