### PR TITLE
LPS-83156 Prevents ActionURLScreens from being cached and reused on consecutive actions causing lifecycle events to be executed on the live document instead of on temporary fragments

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brunobasto, @matuzalemsteles, @diegonvs, could you please take a look at this issue? I've been trying to track it down for a while and finally had some (unofficial) time to properly look into it 🎄🎅 

This should be addressing [LPS-83156](https://issues.liferay.com/browse/LPS-83156) and [LPS-85567](https://issues.liferay.com/browse/LPS-85567)

I think there's some inherently bad code in `senna.js`, but I'm not 100% sure if we'd want to try a deeper fix at this point. To me, it seems that the way we [cache screens on `createScreenInstance`](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L367-L377) is the underlying problem.

This is what happens and is uncovered by the attached LPSs:
- We successfully navigate one time to a specific path
- We start a second navigation (to the same path)
- When calling [`createScreenInstance`](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L367-L377) we return the same screen (`activeScreen`)
- After loading the next content, we call [`prepareNavigateSurfaces_`](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L435) on the cached screen
- We then [add the new content onto the surface on the cached screen](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L1160)
-  ⚠️ At this point, the new content is already live in the document and not in an external fragment as it will usually happen
- When we call the [`beforeScreenFlip`](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L442) lifecycle, we will be acting on the live content already rather than on the old one. Calling things like `dispose` methods or any other dom mutations will change the live DOM, providing an unknown state to `evaluateScripts` when called later. 

Please, could you take a look and discuss this together to see if you can find a better general solution? If not, I hope this can be good enough in the meantime.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @brunobasto, @matuzalemsteles, did you have a chance to take a look? Do you think this is safe or do we have something better?

If you don't have any other insights, can you take a quick look and push it forward?

Thanks! :)

**Comment by brunobasto** [comment]
Hey @jbalsas, Matu is still on vacations until next Tuesday and I just got back. I'll try to go over it tomorrow.
Thx

**Comment by jbalsas** [comment]
That's fine @brunobasto, don't worry! I just wanted a quick assessment from you. If you think we should look somewhere else, either Matu or myself will take care of this. I don't want to burden you with this anymore than necessary :)

Thanks!

**Comment by brunobasto** [comment]
Hey @jbalsas, no worries!

I think I understand your solution, but I'm thinking if this could be a bug of the cache feature. Because we already say that ActionURLScreen should not be cached: https://github.com/brunobasto/liferay-portal/blob/ca0a70462b5229c86469ce596a1cd3dc4ea8e7b4/modules/apps/frontend-js/frontend-js-spa-web/src/main/resources/META-INF/resources/liferay/screen/EventScreen.es.js#L24

So I'm not sure if it should be an internal implementation of senna to not reuse instances of uncacheable screens.. What do you think?

**Comment by jbalsas** [comment]
Hey @brunobasto!

Yeah, I definitely think this is an issue inside the Senna implementation, but I think it might be rather tricky and risky to fix, which is why I didn't attempt it right away.

We're [using `cacheable` to `dispose` the screens after a successful navigation](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L482-L486). So far, that's the only implication of setting the `cacheable=false` flag in a Screen, and so far, it's working as intended.

We could use `if (!screen || !screen.cacheable)` to avoid [returning non cacheable screens](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L368). The main problem, which is what scares me, is that [`removeScreen`](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L1186) takes a string as entry parameter and not a screen. All the screens are stored and retrieved from `this.screens[path]`, which complicates the logic when going from one path to the same one. We could:
- Add some similar logic to the one in this PR to avoid naming collisions
- Always pass the screens around rather than relying on `this.screens[path]`.

I'm a bit afraid to introduce either directly in Senna, but if you think it's worth it, I can give it a try!

**Comment by brunobasto** [comment]
I agree it's safer not to introduce it in senna right now. Was just trying to make sense of the cache feature we have there and if this was something that should be fixed on that level. But I'd rather be on the safer side.

Do you want me to send this forward?

Thx!

**Comment by jbalsas** [comment]
If it makes sense after this conversation, then yes, please, send it forward :)

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66372. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
