### PR TITLE
LPS-110012/LPS-110013

### PR DESCRIPTION
**Pull request by mateomustapic**
Replace AlloyEditor  in Title and Description fields in Forms

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1140. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/10f30474bd5f~3...10f30474bd5f)

**Pull request closed without merging**
