### PR TITLE
LPS-65870 - SPA - forms are submitted via senna.js even when portlet has been blacklisted

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Bruno,

Attached is another update for https://issues.liferay.com/browse/LPS-65870.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@mjbradford89 @brunobasto, does this need to go into DXP?

**Comment by shinnlok** [comment]
@kenjiheigel 

If possible yes. Without it a major functionality in Sync does not work.

**Comment by kenjiheigel** [comment]
The apparent failures on this pull aren't real failures. I checked on testray and the functional tests are good. 
https://testray.liferay.com/home/-/testray/runs/46642603/details

**Comment by brunobasto** [comment]
@mjbradford89 I saw you already sent it to bchan, so I'm closing this one.

Thx

**Pull request closed without merging**
