### PR TITLE
LPS-94087 Add missing props parameters related to Element Sets required by IE11

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76660. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/75f06551b96d~1...75f06551b96d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
