### PR TITLE
LPS-95525 Overwrite Clay's toogle-switch-label max width to none to have the same visual result on IE11 and other browsers

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :)

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77445.

**Pull request closed without merging**
