### PR TITLE
LPS-68751 buildLang

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@brunobasto we have changed the behavior of redirect on form builder. Only when the user clicks back or cancel the browser is redirected to the form list, so after saving or publishing a form the page is not redirected. I have experienced a SPA issue when I try to go back to form list after saving the form twice. 

Please forward to @marcellustavares when you're done. 

@macellustavares, please forward to @vicnate5 as we have some Poshi tests broken.

Thanks.

**Comment by leoadb** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
@leoadb this is a real failure, SF is breaking.

**Comment by leoadb** [comment]
@marcellustavares Fixed !! Thanks.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Closed as requested by the team.

**Comment by brunobasto** [comment]
Reopened as requested by the team.

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/kenjiheigel/liferay-portal/pull/310. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/f871b8f~1...f871b8f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
