### PR TITLE
pull-request-40925

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brunobasto see https://github.com/brianchandotcom/liferay-portal/pull/40925

Thx

**Comment by vicnate5** [comment]
ci:retest

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@brunobasto Make sure this does a full run on the PR tester at some point. The poshi test for this change will run.

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41181. [See changes here.](https://github.com/brunobasto/liferay-portal/compare/b23129f~0...b23129f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
