### PR TITLE
LPS-91185 Change to get correct default language from data definition

### PR DESCRIPTION
**Pull request by mclomello**
@brunobasto could u review this pr?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/510. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
